services:
  - type: web
    name: analytics-scripts-api
    env: python
    plan: starter  # Можете изменить на standard или pro при необходимости
    region: oregon  # Или другой регион по выбору
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install chromium --with-deps
      python -c "import nltk; nltk.download('stopwords', download_dir='/opt/render/project/src/nltk_data')"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    
    # Переменные окружения
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: TZ
        value: "Europe/Moscow"
      - key: ENVIRONMENT
        value: "production"
      - key: NLTK_DATA
        value: "/opt/render/project/src/nltk_data"
      
      # BigQuery настройки
      - key: BQ_PROJECT_ID
        value: "codellon-dwh"
      - key: BQ_DATASET_ID  
        value: "amplitude_session_replay"
      - key: BQ_TABLE_EVENTS
        value: "EVENTS_258068"
      - key: BQ_TABLE_COMPLETE
        value: "replay_text_complete"

      # OCR настройки
      - key: BQ_SOURCE_TABLE
        value: "session_replay_urls"
      - key: BQ_TARGET_TABLE
        value: "replay_text_complete"
      - key: TESSDATA_PREFIX
        value: "/usr/share/tesseract-ocr/5/tessdata/"

      # Amplitude настройки
      - key: AMPLITUDE_PROJECT_ID
        value: "258068"
      
      # Настройки скриптов
      - key: MIN_DURATION_SECONDS
        value: "20"
      - key: DAYS_BACK
        value: "2"
      
      # Пути к файлам (будут настроены через Secret Files)
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: "/etc/secrets/bigquery-credentials.json"
      - key: COOKIES_PATH
        value: "/etc/secrets/cookies_new.json"
      
      # Добавьте ваши секретные переменные через Render UI:
      # - GOOGLE_APPLICATION_CREDENTIALS (путь к JSON файлу с credentials)
      # - OPENAI_API_KEY
      # - BQ_PROJECT_ID (если нужно переопределить)
      # - GDRIVE_FOLDER_ID (если нужно переопределить)
    
    # Настройки для автоматического деплоя
    autoDeploy: true
    
    # Проверки здоровья
    healthCheckPath: /health
    
    # Диск для временных файлов (если нужен больший объем)
    disk:
      name: analytics-disk
      mountPath: /tmp
      sizeGB: 1